load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "reasoning_v1",
    srcs = ["reasoning_v1.py"],
    deps = [
        "//proto:telemetry_py_grpc",
    ],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "reasoning_v2",
    srcs = ["reasoning_v2.py"],
    deps = [
        "//proto:telemetry_py_grpc",
    ],
    visibility = ["//visibility:public"],
)
