# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"W\n\x0fWorkloadPayload\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x01(\t\x12\x11\n\tprecision\x18\x03 \x01(\t\x12\x16\n\x0etarget_profile\x18\x04 \x01(\t\"&\n\rRouteDecision\x12\x15\n\rselected_path\x18\x01 \x01(\t\"l\n\x0fHardwareMetrics\x12\x0e\n\x06\x63ycles\x18\x01 \x01(\x04\x12\x14\n\x0c\x63\x61\x63he_misses\x18\x02 \x01(\x04\x12\x1b\n\x13sve_sme_utilization\x18\x03 \x01(\x01\x12\x16\n\x0etarget_profile\x18\x04 \x01(\t\"M\n\x14OptimizationFeedback\x12\x16\n\x0eloop_unrolling\x18\x01 \x01(\x08\x12\x1d\n\x15vector_register_width\x18\x02 \x01(\x05\x32\xb7\x01\n\x15TelemetryOrchestrator\x12\x45\n\rRouteWorkload\x12\x1a.telemetry.WorkloadPayload\x1a\x18.telemetry.RouteDecision\x12W\n\x18\x41nalyzeHardwareTelemetry\x12\x1a.telemetry.HardwareMetrics\x1a\x1f.telemetry.OptimizationFeedbackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKLOADPAYLOAD']._serialized_start=30
  _globals['_WORKLOADPAYLOAD']._serialized_end=117
  _globals['_ROUTEDECISION']._serialized_start=119
  _globals['_ROUTEDECISION']._serialized_end=157
  _globals['_HARDWAREMETRICS']._serialized_start=159
  _globals['_HARDWAREMETRICS']._serialized_end=267
  _globals['_OPTIMIZATIONFEEDBACK']._serialized_start=269
  _globals['_OPTIMIZATIONFEEDBACK']._serialized_end=346
  _globals['_TELEMETRYORCHESTRATOR']._serialized_start=349
  _globals['_TELEMETRYORCHESTRATOR']._serialized_end=532
# @@protoc_insertion_point(module_scope)
