# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryOrchestratorStub(object):
    """The central orchestrator service for hardware/software co-design.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteWorkload = channel.unary_unary(
                '/telemetry.TelemetryOrchestrator/RouteWorkload',
                request_serializer=telemetry__pb2.WorkloadPayload.SerializeToString,
                response_deserializer=telemetry__pb2.RouteDecision.FromString,
                _registered_method=True)
        self.AnalyzeHardwareTelemetry = channel.unary_unary(
                '/telemetry.TelemetryOrchestrator/AnalyzeHardwareTelemetry',
                request_serializer=telemetry__pb2.HardwareMetrics.SerializeToString,
                response_deserializer=telemetry__pb2.OptimizationFeedback.FromString,
                _registered_method=True)


class TelemetryOrchestratorServicer(object):
    """The central orchestrator service for hardware/software co-design.
    """

    def RouteWorkload(self, request, context):
        """Routes a workload to the ideal execution hardware based on metrics and target profiles.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeHardwareTelemetry(self, request, context):
        """Analyzes hardware telemetry from FVP runs to recommend architectural/compilation parameters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteWorkload': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteWorkload,
                    request_deserializer=telemetry__pb2.WorkloadPayload.FromString,
                    response_serializer=telemetry__pb2.RouteDecision.SerializeToString,
            ),
            'AnalyzeHardwareTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeHardwareTelemetry,
                    request_deserializer=telemetry__pb2.HardwareMetrics.FromString,
                    response_serializer=telemetry__pb2.OptimizationFeedback.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.TelemetryOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetry.TelemetryOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryOrchestrator(object):
    """The central orchestrator service for hardware/software co-design.
    """

    @staticmethod
    def RouteWorkload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.TelemetryOrchestrator/RouteWorkload',
            telemetry__pb2.WorkloadPayload.SerializeToString,
            telemetry__pb2.RouteDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeHardwareTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.TelemetryOrchestrator/AnalyzeHardwareTelemetry',
            telemetry__pb2.HardwareMetrics.SerializeToString,
            telemetry__pb2.OptimizationFeedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
