apiVersion: v1
kind: Service
metadata:
  name: mvcp-envoy-service
  labels:
    app: mvcp-control-plane
spec:
  type: LoadBalancer
  selector:
    app: mvcp-control-plane
  ports:
  - port: 10000
    targetPort: 10000
    protocol: TCP
    name: envoy-gateway
