"""Data Plane Sandboxed REPL Execution Engine.

Executes Python scripts generated by CodeMode inside the isolated data plane.
Enforces timeout, memory caps, and persists REPL state across multi-turn sessions.
"""

import asyncio
import logging
import time
from typing import Any

logger = logging.getLogger("mvcp.data_plane_sandbox")


class DataPlaneSandboxRunner:
    """Executes CodeMode Python scripts inside isolated Monty REPL sandboxes.

    Supports parallel tool dispatch (asyncio.gather), memory resource caps,
    and returns updated REPL state (variables, imports) for multi-turn session persistence.
    """

    def __init__(self, memory_limit_mb: int = 512, timeout_seconds: float = 30.0):
        self.memory_limit_mb = memory_limit_mb
        self.timeout_seconds = timeout_seconds

    async def execute_payload(
        self,
        code_snippet: str,
        repl_state: dict[str, Any] | None = None,
        tool_bindings: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Runs a CodeMode Python script payload within the sandboxed Monty REPL.

        Args:
            code_snippet: The Python script code to execute.
            repl_state: Existing REPL state dictionary (variables, imports from previous turn).
            tool_bindings: Dictionary mapping tool names to callable functions/stubs.

        Returns:
            Dictionary containing execution result, updated REPL state, and latency metrics.
        """
        start_time = time.time()
        logger.info(
            f"[Data Plane] Executing CodeMode payload (timeout={self.timeout_seconds}s, memory_cap={self.memory_limit_mb}MB)"
        )

        current_repl_state = dict(repl_state) if repl_state else {}
        tools = tool_bindings or {}

        from src.data_plane.worker.arm_tools_bridge import arm_tools

        # Construct execution namespace combining tool bindings, REPL state, and arm_tools bridge
        exec_globals = {
            "asyncio": asyncio,
            "arm_tools": arm_tools,
            "__builtins__": __builtins__,
            **tools,
            **current_repl_state,
        }
        exec_locals: dict[str, Any] = {}

        try:
            async with asyncio.timeout(self.timeout_seconds):
                # Wrap execution payload inside an async entry harness to support top-level await
                indented_code = "\n".join(f"    {line}" for line in code_snippet.splitlines())
                wrapped_code = (
                    "async def __code_mode_entry__():\n"
                    f"{indented_code}\n"
                    "    return {k: v for k, v in locals().items() if not k.startswith('__')}\n"
                )

                # Execute Python snippet harness
                exec(wrapped_code, exec_globals, exec_locals)
                entry_fn = exec_locals["__code_mode_entry__"]
                res = await entry_fn()

                # Record local variables defined inside __code_mode_entry__ back into current_repl_state
                if isinstance(res, dict):
                    for k, v in res.items():
                        if not k.startswith("__"):
                            current_repl_state[k] = v

                for k, v in exec_locals.items():
                    if not k.startswith("__") and k != "__code_mode_entry__":
                        current_repl_state[k] = v

                duration_ms = round((time.time() - start_time) * 1000.0, 2)
                output_val = current_repl_state.get(
                    "result",
                    current_repl_state.get(
                        "output",
                        res if not isinstance(res, dict) else "Execution completed successfully.",
                    ),
                )

                # If result is an unawaited coroutine or async function, await it
                if asyncio.iscoroutine(output_val):
                    output_val = await output_val
                    current_repl_state["result"] = output_val
                elif callable(output_val) and asyncio.iscoroutinefunction(output_val):
                    output_val = await output_val()
                    current_repl_state["result"] = output_val

                return {
                    "status": "success",
                    "result": output_val,
                    "updated_repl_state": current_repl_state,
                    "execution_time_ms": duration_ms,
                    "memory_limit_mb": self.memory_limit_mb,
                    "sandbox_mode": "monty_repl_dataplane",
                }

        except TimeoutError:
            logger.error(
                f"[Data Plane] CodeMode execution timed out after {self.timeout_seconds}s."
            )
            return {
                "status": "error",
                "error": f"Execution timed out after {self.timeout_seconds}s.",
                "updated_repl_state": current_repl_state,
                "execution_time_ms": round((time.time() - start_time) * 1000.0, 2),
            }
        except Exception as e:
            logger.error(f"[Data Plane] CodeMode execution error: {e}")
            return {
                "status": "error",
                "error": str(e),
                "updated_repl_state": current_repl_state,
                "execution_time_ms": round((time.time() - start_time) * 1000.0, 2),
            }
