load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_proto_grpc_cpp//:defs.bzl", "cpp_grpc_library")
load("@rules_proto_grpc_python//:defs.bzl", "python_grpc_library")

package(default_visibility = ["//visibility:public"])

# Base protobuf schema target
proto_library(
    name = "telemetry_proto",
    srcs = ["telemetry.proto"],
)

# Generates C++ protobuf + gRPC and bundles them into a cc_library target
cpp_grpc_library(
    name = "telemetry_cc_grpc",
    protos = [":telemetry_proto"],
)

# Generates Python protobuf + gRPC and bundles them into a py_library target
python_grpc_library(
    name = "telemetry_py_grpc",
    protos = [":telemetry_proto"],
)
