apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  arm-internal.override: |
    rewrite name exact keycloak.arm.internal keycloak-service.default.svc.cluster.local
    rewrite name exact gateway.arm.internal envoy-edge-guard-service.default.svc.cluster.local
